local armor_data = {}

armor_data.armor_all = {
    { value = [[
[GLOVES:ITEM_GLOVES_NULL:FORCED]
[SHOES:ITEM_SHOES_NULL:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_UL_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_LT_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_MD_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_HV_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_SH_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_UL_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_LT_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_MD_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_HV_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_SH_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_UL_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_LT_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_MD_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_HV_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_SH_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_UL_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_LT_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_MD_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_HV_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_BLOK_SH_FG:FORCED]
]], weight = 10, 
next_level_tables = {
"helm_block"
 }
},
    { value = [[
[GLOVES:ITEM_GLOVES_NULL:FORCED]
[SHOES:ITEM_SHOES_NULL:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_UL_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_LT_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_MD_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_HV_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_SH_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_UL_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_LT_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_MD_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_HV_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_SH_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_UL_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_LT_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_MD_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_HV_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_SH_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_UL_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_LT_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_MD_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_HV_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CYLN_SH_FG:FORCED]
]], weight = 10, 
next_level_tables = {
"helm_block"
 }
},

    { value = [[
[GLOVES:ITEM_GLOVES_NULL:FORCED]
[SHOES:ITEM_SHOES_NULL:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_UL_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_LT_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_MD_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_HV_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_SH_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_UL_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_LT_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_MD_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_HV_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_SH_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_UL_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_LT_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_MD_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_HV_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_SH_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_UL_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_LT_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_MD_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_HV_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_WDGE_SH_FG:FORCED]
]], weight = 10, 
next_level_tables = {
"helm_edge"
 }
},

    { value = [[
[GLOVES:ITEM_GLOVES_NULL:FORCED]
[SHOES:ITEM_SHOES_NULL:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_UL_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_LT_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_MD_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_HV_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_SH_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_UL_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_LT_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_MD_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_HV_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_SH_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_UL_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_LT_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_MD_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_HV_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_SH_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_UL_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_LT_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_MD_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_HV_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_PYRM_SH_FG:FORCED]
]], weight = 10, 
next_level_tables = {
"helm_edge"
 }
},
    { value = [[
[GLOVES:ITEM_GLOVES_NULL:FORCED]
[SHOES:ITEM_SHOES_NULL:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_UL_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_LT_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_MD_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_HV_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_SH_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_UL_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_LT_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_MD_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_HV_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_SH_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_UL_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_LT_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_MD_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_HV_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_SH_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_UL_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_LT_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_MD_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_HV_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_OBLT_SH_FG:FORCED]
]], weight = 10, 
next_level_tables = {
"helm_round"
 }
},

    { value = [[
[GLOVES:ITEM_GLOVES_NULL:FORCED]
[SHOES:ITEM_SHOES_NULL:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_UL_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_LT_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_MD_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_HV_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_SH_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_UL_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_LT_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_MD_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_HV_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_SH_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_UL_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_LT_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_MD_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_HV_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_SH_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_UL_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_LT_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_MD_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_HV_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_CONE_SH_FG:FORCED]
]], weight = 10, 
next_level_tables = {
"helm_cone"
 }
},

    { value = [[
[GLOVES:ITEM_GLOVES_NULL:FORCED]
[SHOES:ITEM_SHOES_NULL:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_UL_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_LT_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_MD_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_HV_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_SH_NG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_UL_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_LT_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_MD_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_HV_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_SH_AG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_UL_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_LT_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_MD_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_HV_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_SH_LG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_UL_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_LT_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_MD_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_HV_FG:FORCED]
[ARMOR:ITEM_ARMOR_CORE_SPHR_SH_FG:FORCED]
]], weight = 10, 
next_level_tables = {
"helm_round"
 }
},


}




armor_data.helm_block = {
    { value = [[
[HELM:ITEM_HELM_BKWD_BLOK_STRT:FORCED]
[HELM:ITEM_HELM_BKWD_BLOK_UPWD:FORCED]
[HELM:ITEM_HELM_BODY_BLOK:FORCED]
[HELM:ITEM_HELM_BROD_BLOK_STRT:FORCED]
[HELM:ITEM_HELM_BROD_BLOK_V_BKWD:FORCED]
[HELM:ITEM_HELM_BROD_BLOK_V_FRWD:FORCED]
[HELM:ITEM_HELM_BROD_BLOK_V_UPWD:FORCED]
[HELM:ITEM_HELM_FRWD_BLOK_DNWD:FORCED]
[HELM:ITEM_HELM_FRWD_BLOK_STRT:FORCED]
[HELM:ITEM_HELM_SKUL_BLOK:FORCED]
[HELM:ITEM_HELM_TALL_BLOK_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_BLOK_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_BLOK_STRT:FORCED]
]], weight = 3, 
next_level_tables = {
"limbs_block"
 }
 },
    { value = [[
[HELM:ITEM_HELM_BKWD_CYLN_STRT:FORCED]
[HELM:ITEM_HELM_BKWD_CYLN_UPWD:FORCED]
[HELM:ITEM_HELM_BODY_CYLN:FORCED]
[HELM:ITEM_HELM_BROD_CYLN_STRT:FORCED]
[HELM:ITEM_HELM_BROD_CYLN_V_BKWD:FORCED]
[HELM:ITEM_HELM_BROD_CYLN_V_FRWD:FORCED]
[HELM:ITEM_HELM_BROD_CYLN_V_UPWD:FORCED]
[HELM:ITEM_HELM_FLAT_CYLN:FORCED]
[HELM:ITEM_HELM_FRWD_CYLN_STRT:FORCED]
[HELM:ITEM_HELM_FRWD_CYLN_UPWD:FORCED]
[HELM:ITEM_HELM_SKUL_CYLN:FORCED]
[HELM:ITEM_HELM_TALL_CYLN_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_CYLN_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_CYLN_STRT:FORCED]
]], weight = 1, 
next_level_tables = {
"limbs_cylinder"
 }
 },
    { value = [[
[HELM:ITEM_HELM_BODY_WDGE:FORCED]
[HELM:ITEM_HELM_BROD_WDGE_STRT:FORCED]
[HELM:ITEM_HELM_BROD_WDGE_V_BKWD:FORCED]
[HELM:ITEM_HELM_BROD_WDGE_V_FRWD:FORCED]
[HELM:ITEM_HELM_BROD_WDGE_V_UPWD:FORCED]
[HELM:ITEM_HELM_FLAT_WDGE:FORCED]
[HELM:ITEM_HELM_FRWD_WDGE_DNWD:FORCED]
[HELM:ITEM_HELM_FRWD_WDGE_STRT:FORCED]
[HELM:ITEM_HELM_FRWD_WDGE_UPWD:FORCED]
[HELM:ITEM_HELM_SKUL_WDGE:FORCED]
[HELM:ITEM_HELM_TALL_WDGE_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_WDGE_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_WDGE_STRT:FORCED]
]], weight = 1, 
next_level_tables = {
"limbs_wedge"
 }
 },
}


armor_data.helm_round = {
    { value = [[
[HELM:ITEM_HELM_BKWD_OBLG_STRT:FORCED]
[HELM:ITEM_HELM_BKWD_OBLG_UPWD:FORCED]
[HELM:ITEM_HELM_BODY_OBLG:FORCED]
[HELM:ITEM_HELM_BROD_OBLG_STRT:FORCED]
[HELM:ITEM_HELM_BROD_OBLG_V_BKWD:FORCED]
[HELM:ITEM_HELM_BROD_OBLG_V_FRWD:FORCED]
[HELM:ITEM_HELM_BROD_OBLG_V_UPWD:FORCED]
[HELM:ITEM_HELM_FRWD_OBLG_DNWD:FORCED]
[HELM:ITEM_HELM_FRWD_OBLG_STRT:FORCED]
[HELM:ITEM_HELM_FRWD_OBLG_UPWD:FORCED]
[HELM:ITEM_HELM_SKUL_OBLG:FORCED]
[HELM:ITEM_HELM_BODY_SPHR:FORCED]
[HELM:ITEM_HELM_SKUL_SPHR:FORCED]
[HELM:ITEM_HELM_FLAT_EPSL:FORCED]
]], weight = 3, 
next_level_tables = {
"limbs_oblong"
 }
 },
    { value = [[
[HELM:ITEM_HELM_BODY_OBLT:FORCED]
[HELM:ITEM_HELM_SKUL_OBLT:FORCED]
[HELM:ITEM_HELM_TALL_OBLT_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_OBLT_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_OBLT_STRT:FORCED]
[HELM:ITEM_HELM_BODY_SPHR:FORCED]
[HELM:ITEM_HELM_SKUL_SPHR:FORCED]
[HELM:ITEM_HELM_FLAT_EPSL:FORCED]
]], weight = 1, 
next_level_tables = {
"limbs_oblate"
 }
 },
    { value = [[
[HELM:ITEM_HELM_BKWD_CSNT_UPWD:FORCED]
[HELM:ITEM_HELM_BROD_CSNT_STRT:FORCED]
[HELM:ITEM_HELM_BROD_CSNT_V_BKWD:FORCED]
[HELM:ITEM_HELM_BROD_CSNT_V_FRWD:FORCED]
[HELM:ITEM_HELM_BROD_CSNT_V_UPWD:FORCED]
[HELM:ITEM_HELM_FRWD_CSNT_DNWD:FORCED]
[HELM:ITEM_HELM_FRWD_CSNT_STRT:FORCED]
[HELM:ITEM_HELM_FRWD_CSNT_UPWD:FORCED]
[HELM:ITEM_HELM_TALL_CSNT_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_CSNT_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_CSNT_STRT:FORCED]
]], weight = 1, 
next_level_tables = {
"limbs_crescent"
 }
 },
    { value = [[
[HELM:ITEM_HELM_BKWD_CRST_STRT:FORCED]
[HELM:ITEM_HELM_BKWD_CRST_UPWD:FORCED]
[HELM:ITEM_HELM_TALL_CRST_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_CRST_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_CRST_STRT:FORCED]
[HELM:ITEM_HELM_BKWD_FLRE_DNWD:FORCED]
[HELM:ITEM_HELM_BKWD_FLRE_STRT:FORCED]
[HELM:ITEM_HELM_BKWD_FLRE_UPWD:FORCED]
[HELM:ITEM_HELM_FLAT_FLRE:FORCED]
[HELM:ITEM_HELM_SKUL_FLRE:FORCED]
[HELM:ITEM_HELM_TALL_FLRE_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_FLRE_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_FLRE_STRT:FORCED]
]], weight = 1, 
next_level_tables = {
"limbs_flare"
 }
 },
    { value = [[
[HELM:ITEM_HELM_BKWD_HOOK_DNWD:FORCED]
[HELM:ITEM_HELM_BKWD_HOOK_STRT:FORCED]
[HELM:ITEM_HELM_FRWD_HOOK_STRT:FORCED]
[HELM:ITEM_HELM_FRWD_HOOK_UPWD:FORCED]
[HELM:ITEM_HELM_BKWD_CRST_STRT:FORCED]
[HELM:ITEM_HELM_BKWD_CRST_UPWD:FORCED]
[HELM:ITEM_HELM_TALL_CRST_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_CRST_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_CRST_STRT:FORCED]
[HELM:ITEM_HELM_FLAT_FLRE:FORCED]
[HELM:ITEM_HELM_SKUL_FLRE:FORCED]
]], weight = 1, 
next_level_tables = {
"limbs_hook"
 }
 },
}




armor_data.helm_edge = {
    { value = [[
[HELM:ITEM_HELM_BKWD_PYRM_DNWD:FORCED]
[HELM:ITEM_HELM_BKWD_PYRM_STRT:FORCED]
[HELM:ITEM_HELM_BKWD_PYRM_UPWD:FORCED]
[HELM:ITEM_HELM_BROD_PYRM_STRT:FORCED]
[HELM:ITEM_HELM_BROD_PYRM_V_BKWD:FORCED]
[HELM:ITEM_HELM_BROD_PYRM_V_FRWD:FORCED]
[HELM:ITEM_HELM_BROD_PYRM_V_UPWD:FORCED]
[HELM:ITEM_HELM_FRWD_PYRM_DNWD:FORCED]
[HELM:ITEM_HELM_FRWD_PYRM_STRT:FORCED]
[HELM:ITEM_HELM_FRWD_PYRM_UPWD:FORCED]
[HELM:ITEM_HELM_TALL_PYRM_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_PYRM_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_PYRM_STRT:FORCED]
]], weight = 3, 
next_level_tables = {
"limbs_pyramid"
 }
 },
    { value = [[
[HELM:ITEM_HELM_BODY_WDGE:FORCED]
[HELM:ITEM_HELM_BROD_WDGE_STRT:FORCED]
[HELM:ITEM_HELM_BROD_WDGE_V_BKWD:FORCED]
[HELM:ITEM_HELM_BROD_WDGE_V_FRWD:FORCED]
[HELM:ITEM_HELM_BROD_WDGE_V_UPWD:FORCED]
[HELM:ITEM_HELM_FLAT_WDGE:FORCED]
[HELM:ITEM_HELM_FRWD_WDGE_DNWD:FORCED]
[HELM:ITEM_HELM_FRWD_WDGE_STRT:FORCED]
[HELM:ITEM_HELM_FRWD_WDGE_UPWD:FORCED]
[HELM:ITEM_HELM_SKUL_WDGE:FORCED]
[HELM:ITEM_HELM_TALL_WDGE_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_WDGE_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_WDGE_STRT:FORCED]
]], weight = 1, 
next_level_tables = {
"limbs_wedge"
 }
 },
    { value = [[
[HELM:ITEM_HELM_BKWD_CSNT_UPWD:FORCED]
[HELM:ITEM_HELM_BROD_CSNT_STRT:FORCED]
[HELM:ITEM_HELM_BROD_CSNT_V_BKWD:FORCED]
[HELM:ITEM_HELM_BROD_CSNT_V_FRWD:FORCED]
[HELM:ITEM_HELM_BROD_CSNT_V_UPWD:FORCED]
[HELM:ITEM_HELM_FRWD_CSNT_DNWD:FORCED]
[HELM:ITEM_HELM_FRWD_CSNT_STRT:FORCED]
[HELM:ITEM_HELM_FRWD_CSNT_UPWD:FORCED]
[HELM:ITEM_HELM_TALL_CSNT_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_CSNT_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_CSNT_STRT:FORCED]
]], weight = 1, 
next_level_tables = {
"limbs_crescent"
 }
 },
    { value = [[
[HELM:ITEM_HELM_SKUL_CONE:FORCED]
[HELM:ITEM_HELM_FRWD_CONE_DNWD:FORCED]
[HELM:ITEM_HELM_FRWD_CONE_STRT:FORCED]
[HELM:ITEM_HELM_FRWD_CONE_UPWD:FORCED]
[HELM:ITEM_HELM_TALL_CONE_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_CONE_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_CONE_STRT:FORCED]
]], weight = 1, 
next_level_tables = {
"limbs_cone"
 }
 },
}


armor_data.helm_cone = {
    { value = [[
[HELM:ITEM_HELM_BKWD_CSNT_UPWD:FORCED]
[HELM:ITEM_HELM_BROD_CSNT_STRT:FORCED]
[HELM:ITEM_HELM_BROD_CSNT_V_BKWD:FORCED]
[HELM:ITEM_HELM_BROD_CSNT_V_FRWD:FORCED]
[HELM:ITEM_HELM_BROD_CSNT_V_UPWD:FORCED]
[HELM:ITEM_HELM_FRWD_CSNT_DNWD:FORCED]
[HELM:ITEM_HELM_FRWD_CSNT_STRT:FORCED]
[HELM:ITEM_HELM_FRWD_CSNT_UPWD:FORCED]
[HELM:ITEM_HELM_TALL_CSNT_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_CSNT_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_CSNT_STRT:FORCED]
[HELM:ITEM_HELM_SKUL_CONE:FORCED]
[HELM:ITEM_HELM_FRWD_CONE_DNWD:FORCED]
[HELM:ITEM_HELM_FRWD_CONE_STRT:FORCED]
[HELM:ITEM_HELM_FRWD_CONE_UPWD:FORCED]
[HELM:ITEM_HELM_TALL_CONE_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_CONE_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_CONE_STRT:FORCED]
]], weight = 1, 
next_level_tables = {
"limbs_crescent"
 }
 },
    { value = [[
[HELM:ITEM_HELM_SKUL_CONE:FORCED]
[HELM:ITEM_HELM_FRWD_CONE_DNWD:FORCED]
[HELM:ITEM_HELM_FRWD_CONE_STRT:FORCED]
[HELM:ITEM_HELM_FRWD_CONE_UPWD:FORCED]
[HELM:ITEM_HELM_TALL_CONE_BKWD:FORCED]
[HELM:ITEM_HELM_TALL_CONE_FRWD:FORCED]
[HELM:ITEM_HELM_TALL_CONE_STRT:FORCED]
]], weight = 1, 
next_level_tables = {
"limbs_cone"
 }
 },
}


armor_data.limbs_block = {
    { value = [[
[GLOVES:ITEM_GLOVES_BLOK_GARD:FORCED]
[GLOVES:ITEM_GLOVES_BLOK_SHLD:FORCED]
[SHOES:ITEM_SHOES_BLOK_GARD:FORCED]
[SHOES:ITEM_SHOES_BLOK_SHLD:FORCED]
]], weight = 1
 },
    { value = [[

[GLOVES:ITEM_GLOVES_CYLN_GARD:FORCED]
[GLOVES:ITEM_GLOVES_CYLN_SHLD:FORCED]
[SHOES:ITEM_SHOES_CYLN_GARD:FORCED]
[SHOES:ITEM_SHOES_CYLN_SHLD:FORCED]
]], weight = 1
 },
}


armor_data.limbs_cone = {
    { value = [[
[GLOVES:ITEM_GLOVES_CONE_GARD:FORCED]
[GLOVES:ITEM_GLOVES_CONE_SHLD:FORCED]
[SHOES:ITEM_SHOES_CONE_GARD:FORCED]
[SHOES:ITEM_SHOES_CONE_SHLD:FORCED]
]], weight = 1
 },
    { value = [[
[GLOVES:ITEM_GLOVES_HOOK_GARD:FORCED]
[GLOVES:ITEM_GLOVES_HOOK_SHLD:FORCED]
[SHOES:ITEM_SHOES_HOOK_GARD:FORCED]
[SHOES:ITEM_SHOES_HOOK_SHLD:FORCED]
]], weight = 1
 },
    { value = [[
[GLOVES:ITEM_GLOVES_EPSL_GARD:FORCED]
[SHOES:ITEM_SHOES_EPSL_GARD:FORCED]
[GLOVES:ITEM_GLOVES_EPSL_SHLD:FORCED]
[SHOES:ITEM_SHOES_EPSL_SHLD:FORCED]
]], weight = 1
 },
}



armor_data.limbs_crescent = {
    { value = [[
[GLOVES:ITEM_GLOVES_FLRE_GARD:FORCED]
[GLOVES:ITEM_GLOVES_FLRE_SHLD:FORCED]
[SHOES:ITEM_SHOES_FLRE_GARD:FORCED]
[SHOES:ITEM_SHOES_FLRE_SHLD:FORCED]
]], weight = 1
 },
    { value = [[

[GLOVES:ITEM_GLOVES_HOOK_GARD:FORCED]
[GLOVES:ITEM_GLOVES_HOOK_SHLD:FORCED]
[SHOES:ITEM_SHOES_HOOK_GARD:FORCED]
[SHOES:ITEM_SHOES_HOOK_SHLD:FORCED]
]], weight = 1
 },
}



armor_data.limbs_cylinder = {
    { value = [[
[GLOVES:ITEM_GLOVES_BLOK_GARD:FORCED]
[GLOVES:ITEM_GLOVES_BLOK_SHLD:FORCED]
[SHOES:ITEM_SHOES_BLOK_GARD:FORCED]
[SHOES:ITEM_SHOES_BLOK_SHLD:FORCED]
]], weight = 1
 },
    { value = [[
[GLOVES:ITEM_GLOVES_CYLN_GARD:FORCED]
[GLOVES:ITEM_GLOVES_CYLN_SHLD:FORCED]
[SHOES:ITEM_SHOES_CYLN_GARD:FORCED]
[SHOES:ITEM_SHOES_CYLN_SHLD:FORCED]
]], weight = 1
 },
    { value = [[
[GLOVES:ITEM_GLOVES_CONE_GARD:FORCED]
[GLOVES:ITEM_GLOVES_CONE_SHLD:FORCED]
[SHOES:ITEM_SHOES_CONE_GARD:FORCED]
[SHOES:ITEM_SHOES_CONE_SHLD:FORCED]
]], weight = 1
 },
    { value = [[
[GLOVES:ITEM_GLOVES_EPSL_GARD:FORCED]
[SHOES:ITEM_SHOES_EPSL_GARD:FORCED]
[GLOVES:ITEM_GLOVES_EPSL_SHLD:FORCED]
[SHOES:ITEM_SHOES_EPSL_SHLD:FORCED]
]], weight = 1
 },
}


armor_data.limbs_flare = {
    { value = [[
[GLOVES:ITEM_GLOVES_FLRE_GARD:FORCED]
[GLOVES:ITEM_GLOVES_FLRE_SHLD:FORCED]
[SHOES:ITEM_SHOES_FLRE_GARD:FORCED]
[SHOES:ITEM_SHOES_FLRE_SHLD:FORCED]
]], weight = 1
 },
    { value = [[

[GLOVES:ITEM_GLOVES_HOOK_GARD:FORCED]
[GLOVES:ITEM_GLOVES_HOOK_SHLD:FORCED]
[SHOES:ITEM_SHOES_HOOK_GARD:FORCED]
[SHOES:ITEM_SHOES_HOOK_SHLD:FORCED]
]], weight = 1
 },
}


armor_data.limbs_hook = {
    { value = [[
[GLOVES:ITEM_GLOVES_HOOK_GARD:FORCED]
[GLOVES:ITEM_GLOVES_HOOK_SHLD:FORCED]
[SHOES:ITEM_SHOES_HOOK_GARD:FORCED]
[SHOES:ITEM_SHOES_HOOK_SHLD:FORCED]
]], weight = 1
 },
    { value = [[

[GLOVES:ITEM_GLOVES_FLRE_GARD:FORCED]
[GLOVES:ITEM_GLOVES_FLRE_SHLD:FORCED]
[SHOES:ITEM_SHOES_FLRE_GARD:FORCED]
[SHOES:ITEM_SHOES_FLRE_SHLD:FORCED]
]], weight = 1
 },
    { value = [[
[GLOVES:ITEM_GLOVES_OBLG_GARD:FORCED]
[GLOVES:ITEM_GLOVES_OBLT_SHLD:FORCED]
[SHOES:ITEM_SHOES_OBLT_GARD:FORCED]
[SHOES:ITEM_SHOES_OBLT_SHLD:FORCED]
]], weight = 1
 },
}


armor_data.limbs_oblate = {
    { value = [[
[GLOVES:ITEM_GLOVES_OBLG_GARD:FORCED]
[GLOVES:ITEM_GLOVES_OBLT_SHLD:FORCED]
[SHOES:ITEM_SHOES_OBLT_GARD:FORCED]
[SHOES:ITEM_SHOES_OBLT_SHLD:FORCED]
]], weight = 2
 },
    { value = [[
[GLOVES:ITEM_GLOVES_SPHR_GARD:FORCED]
[GLOVES:ITEM_GLOVES_SPHR_SHLD:FORCED]
[SHOES:ITEM_SHOES_SPHR_GARD:FORCED]
[SHOES:ITEM_SHOES_OBLT_SHLD:FORCED]

]], weight = 2
 },
    { value = [[
[GLOVES:ITEM_GLOVES_CYLN_GARD:FORCED]
[GLOVES:ITEM_GLOVES_CYLN_SHLD:FORCED]
[SHOES:ITEM_SHOES_CYLN_GARD:FORCED]
[SHOES:ITEM_SHOES_CYLN_SHLD:FORCED]

]], weight = 1
 },
    { value = [[
[GLOVES:ITEM_GLOVES_CONE_GARD:FORCED]
[GLOVES:ITEM_GLOVES_CONE_SHLD:FORCED]
[SHOES:ITEM_SHOES_CONE_GARD:FORCED]
[SHOES:ITEM_SHOES_CONE_SHLD:FORCED]

]], weight = 1
 },
}



armor_data.limbs_oblong = {
    { value = [[
[GLOVES:ITEM_GLOVES_OBLG_GARD:FORCED]
[GLOVES:ITEM_GLOVES_OBLT_SHLD:FORCED]
[SHOES:ITEM_SHOES_OBLT_GARD:FORCED]
[SHOES:ITEM_SHOES_OBLT_SHLD:FORCED]
]], weight = 2
 },
    { value = [[
[GLOVES:ITEM_GLOVES_SPHR_GARD:FORCED]
[GLOVES:ITEM_GLOVES_SPHR_SHLD:FORCED]
[SHOES:ITEM_SHOES_SPHR_GARD:FORCED]
[SHOES:ITEM_SHOES_OBLT_SHLD:FORCED]

]], weight = 2
 },
    { value = [[
[GLOVES:ITEM_GLOVES_CYLN_GARD:FORCED]
[GLOVES:ITEM_GLOVES_CYLN_SHLD:FORCED]
[SHOES:ITEM_SHOES_CYLN_GARD:FORCED]
[SHOES:ITEM_SHOES_CYLN_SHLD:FORCED]

]], weight = 1
 },
    { value = [[
[GLOVES:ITEM_GLOVES_CONE_GARD:FORCED]
[GLOVES:ITEM_GLOVES_CONE_SHLD:FORCED]
[SHOES:ITEM_SHOES_CONE_GARD:FORCED]
[SHOES:ITEM_SHOES_CONE_SHLD:FORCED]

]], weight = 1
 },
}


armor_data.limbs_pyramid = {
    { value = [[
[GLOVES:ITEM_GLOVES_PYRM_GARD:FORCED]
[GLOVES:ITEM_GLOVES_PYRM_SHLD:FORCED]
[SHOES:ITEM_SHOES_PYRM_GARD:FORCED]
[SHOES:ITEM_SHOES_PYRM_SHLD:FORCED]
]], weight = 2
 },
    { value = [[
[GLOVES:ITEM_GLOVES_WDGE_GARD:FORCED]
[GLOVES:ITEM_GLOVES_WDGE_SHLD:FORCED]
[SHOES:ITEM_SHOES_WDGE_GARD:FORCED]
[SHOES:ITEM_SHOES_WDGE_SHLD:FORCED]

]], weight = 1
 },
    { value = [[
[GLOVES:ITEM_GLOVES_BLOK_GARD:FORCED]
[GLOVES:ITEM_GLOVES_BLOK_SHLD:FORCED]
[SHOES:ITEM_SHOES_BLOK_GARD:FORCED]
[SHOES:ITEM_SHOES_BLOK_SHLD:FORCED]

]], weight = 1
 },
}

armor_data.limbs_wedge = {
    { value = [[
[GLOVES:ITEM_GLOVES_PYRM_GARD:FORCED]
[GLOVES:ITEM_GLOVES_PYRM_SHLD:FORCED]
[SHOES:ITEM_SHOES_PYRM_GARD:FORCED]
[SHOES:ITEM_SHOES_PYRM_SHLD:FORCED]
]], weight = 1
 },
    { value = [[
[GLOVES:ITEM_GLOVES_WDGE_GARD:FORCED]
[GLOVES:ITEM_GLOVES_WDGE_SHLD:FORCED]
[SHOES:ITEM_SHOES_WDGE_GARD:FORCED]
[SHOES:ITEM_SHOES_WDGE_SHLD:FORCED]

]], weight = 2
 },
    { value = [[
[GLOVES:ITEM_GLOVES_BLOK_GARD:FORCED]
[GLOVES:ITEM_GLOVES_BLOK_SHLD:FORCED]
[SHOES:ITEM_SHOES_BLOK_GARD:FORCED]
[SHOES:ITEM_SHOES_BLOK_SHLD:FORCED]

]], weight = 1
 },
}




















return {
    armor_data = armor_data
}
